### ISSUE TITLE
[US] Privacy Assurance

### ISSUE THREAD

**Issue by garynks** [uofa-cmput404/404f23project-web-weavers#21]
## User Story
As an author, I want to feel safe about sharing images and posts with my friends – images shared to friends should only be visible to friends. [public images are public]

## Acceptance Tests

**Story Points:** 3

### Code Implementation

- [ ]  [Frontend] ...
- [ ]  [Backend] ...
- [ ]  [Fullstack] Integration

### Code Review
- [ ]  [Frontend] Review
- [ ]  [Backend] Review
- [ ]  [Fullstack] Review

**Comment by Genna-C** [comment]
I think? this one is already done since they can't see FRIENDS posts (unless they cheat our specs)
